(function () {
  "use strict";
  var dictionary={en:{navWork:"WORK",navAbout:"ABOUT",navContact:"CONTACT",heroEyebrow:"SYSTEMS / TENSION / CONSEQUENCE",heroTitle:"I DESIGN<br>RULES THAT<br><em>PUSH BACK.</em>",heroText:"Game designer building playable systems where every choice changes the shape of the next one.",heroCta:"ENTER THE ARCHIVE <span>↓</span>",aboutEyebrow:"THE DESIGNER",aboutTitle:"I make worlds that ask players to <em>pay attention.</em>",aboutText:"I am Lautaro Montoya, a game designer interested in the friction between mechanics and meaning. My work turns unstable spaces, scarce resources, secrets, debt and adaptation into playable decisions.",statProjects:"ORIGINAL PROJECTS",statPillars:"DESIGN PILLARS",statCuriosity:"WAYS TO BREAK A RULE",workEyebrow:"SELECTED PROJECTS",workTitle:"THE <em>PLAYABLE</em> ARCHIVE",workNote:"Click a project to change the signal.",principlesEyebrow:"DESIGN PRINCIPLES",principlesTitle:"A SYSTEM IS A<br><em>CONVERSATION.</em>",p1:"Make rules legible enough to be bent.",p2:"Let resources carry emotional weight.",p3:"Make consequences visible, never arbitrary.",p4:"Leave room for players to surprise themselves.",contactEyebrow:"OPEN TO NEW QUESTS",contactTitle:"LET'S BUILD<br>SOMETHING<br><em>STRANGE.</em>",cvEn:"DOWNLOAD CV — EN ↗",cvEs:"DESCARGAR CV — ES ↗",contactNote:"Portfolio built to be explored.<br>Contact details are available in the CV."},es:{navWork:"PROYECTOS",navAbout:"SOBRE MÍ",navContact:"CONTACTO",heroEyebrow:"SISTEMAS / TENSIÓN / CONSECUENCIA",heroTitle:"DISEÑO REGLAS<br>QUE TE<br><em>RESPONDEN.</em>",heroText:"Game designer que crea sistemas jugables donde cada elección altera la siguiente.",heroCta:"ENTRAR AL ARCHIVO <span>↓</span>",aboutEyebrow:"EL DISEÑADOR",aboutTitle:"Creo mundos que le piden al jugador que <em>preste atención.</em>",aboutText:"Soy Lautaro Montoya, game designer interesado en la fricción entre mecánicas y significado. Mi trabajo convierte espacios inestables, recursos escasos, secretos, deuda y adaptación en decisiones jugables.",statProjects:"PROYECTOS ORIGINALES",statPillars:"PILARES DE DISEÑO",statCuriosity:"FORMAS DE ROMPER UNA REGLA",workEyebrow:"PROYECTOS SELECCIONADOS",workTitle:"EL ARCHIVO <em>JUGABLE</em>",workNote:"Tocá un proyecto para cambiar la señal.",principlesEyebrow:"PRINCIPIOS DE DISEÑO",principlesTitle:"UN SISTEMA ES UNA<br><em>CONVERSACIÓN.</em>",p1:"Hacer las reglas legibles para poder doblarlas.",p2:"Dejar que los recursos tengan peso emocional.",p3:"Volver visibles las consecuencias, nunca arbitrarias.",p4:"Dejar espacio para que el jugador se sorprenda.",contactEyebrow:"ABIERTO A NUEVAS QUESTS",contactTitle:"CONSTRUYAMOS<br>ALGO<br><em>EXTRAÑO.</em>",cvEn:"DESCARGAR CV — EN ↗",cvEs:"DESCARGAR CV — ES ↗",contactNote:"Un portfolio hecho para explorar.<br>Los datos de contacto están en el CV."}};
  var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))},language="en";
  function safe(fn,name){try{fn()}catch(e){console.warn("["+name+"]",e)}}
  function setLanguage(next){language=next;document.documentElement.lang=next;$$("[data-i18n]").forEach(function(el){el.innerHTML=dictionary[next][el.dataset.i18n]||el.innerHTML});$$("[data-es]").forEach(function(el){el.textContent=el.dataset[next]});$(".lang-toggle").classList.toggle("is-es",next==="es");localStorage.setItem("lm-language",next)}
  function initLanguage(){var saved=localStorage.getItem("lm-language");if(saved==="es")setLanguage("es");$(".lang-toggle").addEventListener("click",function(){setLanguage(language==="en"?"es":"en")})}
  function initReveals(){var items=$$(".reveal");if(!("IntersectionObserver" in window)){items.forEach(function(el){el.classList.add("is-visible")});return}var io=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add("is-visible");io.unobserve(entry.target)}})},{threshold:.01,rootMargin:"0px 0px -2% 0px"});items.forEach(function(el){io.observe(el)});setTimeout(function(){$$(".reveal:not(.is-visible)").forEach(function(el){el.classList.add("is-visible")})},6000)}
  function initCoords(){var cursor=$(".cursor-coords"),ready=false;window.addEventListener("mousemove",function(e){cursor.style.left=e.clientX+"px";cursor.style.top=e.clientY+"px";cursor.textContent="["+String(e.clientX).padStart(3,"0")+", "+String(e.clientY).padStart(3,"0")+"]";if(!ready){ready=true;cursor.classList.add("is-ready")}})}
  function initProjects(){$$(".project").forEach(function(card){card.addEventListener("click",function(){document.body.classList.toggle("signal-shift");card.classList.toggle("is-active")})})}
  function initYear(){$("#year").textContent=new Date().getFullYear()}
  function initAnchors(){document.addEventListener("click",function(e){var a=e.target.closest('a[href^="#"]');if(!a)return;var target=$(a.getAttribute("href"));if(!target)return;e.preventDefault();window.scrollTo({top:target.getBoundingClientRect().top+window.scrollY-66,behavior:"smooth"})})}
  function boot(){safe(initLanguage,"language");safe(initReveals,"reveals");safe(initCoords,"coords");safe(initProjects,"projects");safe(initYear,"year");safe(initAnchors,"anchors");setTimeout(function(){$(".splash").style.display="none"},4500)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
